### ISSUE TITLE
Implement Resource page designs

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#10]
https://xd.adobe.com/view/0abb01ec-1d5a-497e-881c-bf7a9ceb064c-5fe8/screen/6fcb8cb6-f118-4bd6-9919-ec0eacf94197

<img width="521" alt="Screen Shot 2021-02-28 at 7 13 16 PM" src="https://user-images.githubusercontent.com/6335974/109447685-115c2080-79f9-11eb-804d-918713b99d92.png">

**Comment by Aujemd** [comment]
Hola Eli quieres que reemplaze el contenido de esta vista con el de ese diseño, cierto?
![Screenshot from 2021-03-23 15-12-45](https://user-images.githubusercontent.com/26072442/112204801-7961e900-8bea-11eb-8b48-5f898a8c49af.png)
![Screenshot from 2021-03-23 15-15-06](https://user-images.githubusercontent.com/26072442/112204944-a4e4d380-8bea-11eb-8486-08ad92baf783.png)

**Comment by Aujemd** [comment]
Si es así, los assets del diseño deben ser los mismos ? o por ahora uso cualquiera

**Comment by eliataylor** [comment]
@Aujemd, yes. 

@polinatolkacheva , can you export the - the light bulb / all possible Badges / coin - from this design and upload them here?

**Comment by polinatolkacheva** [comment]
@eliataylor @Aujemd 

The Coin should be this file (new design): 
![citizencoin_logo_sm](https://user-images.githubusercontent.com/10968182/114251484-08466380-9956-11eb-890e-f71c8510ac0d.png)

The badges for now are:
- Hero Badge (for adding your profile to resources):
![storytellerbadge](https://user-images.githubusercontent.com/10968182/114251822-5c057c80-9957-11eb-9046-d05ee9a8f46e.jpg)

- Storyteller Badge:
![storytellerbadge](https://user-images.githubusercontent.com/10968182/114251860-72abd380-9957-11eb-856b-6c46f6e1ef80.jpeg)

- Scolar Badge:
![scolarbadge](https://user-images.githubusercontent.com/10968182/114251898-9838dd00-9957-11eb-8498-42de5ea56135.jpeg)

- Good Citizen Badge
![goodcitizenbadge](https://user-images.githubusercontent.com/10968182/114251920-af77ca80-9957-11eb-9d96-5734f30332e7.jpeg)

The Graphics on pages are:
Lighbulb:
![lightbulb](https://user-images.githubusercontent.com/10968182/114251952-d33b1080-9957-11eb-82e8-f97ce356ce3f.png)

Action Plan:
![actionplan](https://user-images.githubusercontent.com/10968182/114251988-fbc30a80-9957-11eb-8271-e980fccb6195.png)

**Comment by eliataylor** [comment]
ok.
