### ISSUE TITLE
Add role-based restrictions on the FireCMS

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#15]
Since the CMS seems to expose ALL collections, we need some basic controls, particularly on the Users and Invites collections.

I suggest we prepopulate the Users collection with a few Administrator accounts. Then do something like this 

```
    const myAuthenticator: Authenticator = (user: firebase.User) => {
        if (user.roles.indexOf('admin') > -1) {
           console.log("Allowing access to", user.email);
           return true;
        }
    };
```

All said, depending on how FireCMS gets this access token, we might also need to apply `write` restriction rules directly to Firebase here (https://console.firebase.google.com/u/0/project/democraseeclub/firestore/rules)

**Comment by Branyer** [comment]
ya he agregado una verificacion de roles, y lo he puesto mi correo y el de usted con **ROLE_ADMIN**, en dado caso se podria en un futuro agregar más roles, para manejar quien puede hacer que.

**Comment by eliataylor** [comment]
Ok @Branyer , estas familiar con las reglas de Cloud Firestore?

![Screen Shot 2021-03-09 at 7 54 31 PM](https://user-images.githubusercontent.com/6335974/110574090-4b23da00-8111-11eb-9e84-4fbbaf6aa888.png)

Puedes actualizar la list asi "writes" estan cerrado para todos colleciones menos de `rooms`?

**Comment by Branyer** [comment]
Hola Eli, disculpa que no escribí temprano pero hoy he estado bastante ocupado. Lo que quieres es que: las coleciones que no sean room solo las pueda editar un usuario con role admin, cierto? agregando esa regla de Cloud Firestore.

**Comment by eliataylor** [comment]
casi. 

- si, el CMS es por usuarios con Admin
- si, quiero mas seguridad por los coleciones directamente en Cloud Firestore.  

pero, encima de Roles, el dueño del contenido puedes editar su contenido propio.

me entiendes?

**Comment by Branyer** [comment]
entendido

**Comment by fgatti675** [comment]
Hola @eliataylor y @Branyer !
Soy el creador de FireCMS :) Tenemos previsto hacer un nuevo sistema de roles para el CMS.
De forma muy sencilla, permitira configurar la configuracion de las colecciones basado en que usuario está logueado.
https://github.com/Camberi/firecms/issues/62
Decidme si esto os puede ayudar o si teneis alguna sugerencia o duda al respecto!!
Un saludo

**Comment by Branyer** [comment]
Genial @fgatti675! lo que faltaría seria alguna forma de que el creador de un contenido pueda editarlo o eliminarlo (además del admin), por casualidad, tienes planeado hacer algo así?

**Comment by fgatti675** [comment]
Si, hemos cambiado la granuralidad de los permisos y en la siguiente version, que saldrá en breve, estará disponible :)

**Comment by fgatti675** [comment]
Ok, acabo de publicar la version 0.30.0 que incluye muchos cambios en este sentido.
Se han quitado los flags de `editEnabled` y `deleteEnabled` y reemplazado por un `permissions` (a nivel de coleccion).
El objeto permissions puede establecerse directamente o mediante un builder que recibe la `entity` y el `user` logueado.
Tambien podeis cambiar la navegacion general con un builder del mismo modo.
Decidme si esto os sirve!

**Comment by eliataylor** [comment]
genial y gracias! la funciona bien
