### ISSUE TITLE
Add other OAuth Providers to FireCMS

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#16]
Desde los opciones: https://firebase.google.com/docs/auth/web/firebaseui

@Branyer, empeces con "Email", "Phone", y "Anonymous"

Voy a crear los claves para FB, Twitter, Github, etc....

**Comment by Branyer** [comment]
Ya esta añadido el sign in con Google, Email, telefono y anonimo

**Comment by eliataylor** [comment]
@Branyer , puedes guardar el usuario en Firestore cuando alquien ingresa?

**Comment by eliataylor** [comment]
i'll start a new issue for saving the user after signup/in
