### ISSUE TITLE
Fix multi-way camera / mic / screen sharing

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#2]
- go to https://democraseeclub.web.app/rally/building-democrasee/meeting/2020-11-14
- Select the down arrow next to "Broadcast"
- Enable your Cam/Mic/Screen in the popup
- To close the popup, click outside of it
- Click "Broadcast" and copy the room ID code displayed
- In a **new Browser** or on another computer, go to https://democraseeclub.web.app/rally/building-democrasee/meeting/2020-11-14
- input the code into "Enter Room ID"
- click Connect

ACTUAL RESULTS
-  the host does not get to see the viewing party's broadcast when shared

DESIRED RESULTS
- each party can view the other person's screen (if enabled)
- hosts can see how many people are viewing their own broadcasts

The related files are:

https://github.com/eliataylor/clock-agendas/blob/master/src/components/Room.js
https://github.com/eliataylor/clock-agendas/blob/master/src/components/VideoElement.js
https://github.com/eliataylor/clock-agendas/blob/master/src/components/RemoteVideo.js

**Comment by eliataylor** [comment]
Que bueno @Branyer! Todos los cambios aparecen el camino correcto! Sin embargo, el huespede no puede ver los vistos de otros mirando.

<img width="1782" alt="Screen Shot 2021-02-09 at 1 48 04 PM" src="https://user-images.githubusercontent.com/6335974/107433222-e9565d00-6add-11eb-9734-a44280917ce7.png">

**Comment by eliataylor** [comment]
(y pienso que `https` esta obligatorio para Firebase / RTCPeerConnection)

asi debemos dejar: `HTTPS=true react-scripts start`

**Comment by Branyer** [comment]
Está bien, seguiré buscando la forma de arreglar el problema.

**Comment by Branyer** [comment]
Hola Eli, acabo de subir cambios respecto a este issue.

**Comment by eliataylor** [comment]
@Branyer, yo probé y "Viewers #" funciona, pero todovia el anfitrión no puede ver el huesped

**Comment by Branyer** [comment]
Ya he arreglado lo del anfitrion y el huesped, pruebalo y me comentas. Aun falta algunos detalles, como que si no tiene un broadcast, cuando empiece uno, de inmediato se empiece a transmitir a la otra persona.

**Comment by eliataylor** [comment]
Apparently #12 is necessary to get this working 100%

**Comment by eliataylor** [comment]
@Branyer , yo hize #12 and tengo una nueva rama [rtc-refactor](https://github.com/eliataylor/clock-agendas/blob/rtc-refactor/src/components/Room.js) con muchos cambios para este Issue. 

Yo mantengo la cuenta de vistos correcto, pero no esta compartiendo el Stream. Puedes buscar si tu ves el problema?

**Comment by Branyer** [comment]
voy a revisar

**Comment by eliataylor** [comment]
@Branyer , ves algo?

**Comment by Branyer** [comment]
@eliataylor sí. estuve revisando y el creo que el problema es que en el Room no estas utilizando el component RemoteVideo para renderizar los videos de los viewers ni de los que se entra usando codigo, mañana me pondré a resolver este problema

**Comment by Branyer** [comment]
@eliataylor ya he subido un cambio sobre esto en [rtc-refactor](https://github.com/eliataylor/clock-agendas/tree/rtc-refactor), tengo una pregunta, en este momento la funcionalidad de ver el broadcast de los viewers no funciona, me pregunto si esa funcionalidad se eliminó de la app o tengo que arreglarla para que vuelva a funcionar?

**Comment by eliataylor** [comment]
@Branyer , tu codigo esta en `master` todovia. El problema es el anfitrion del cuarto no puede ver los huespedes.

**Comment by eliataylor** [comment]
sigue en #39
