### ISSUE TITLE
Duplicate firebase & using development build?

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#21]
@Branyer, creo que hay un conflicto entre

https://github.com/eliataylor/clock-agendas/blob/master/public/index.html#L38
y
https://github.com/eliataylor/clock-agendas/blob/master/src/views/firebaseCMS/FirebaseCMS.js#L111

```
logger.ts:115 [2021-03-15T06:09:06.882Z]  @firebase/app: 
    Warning: Firebase is already defined in the global scope. Please make sure
    Firebase library is only loaded once.
```

<img width="1787" alt="Screen Shot 2021-03-14 at 11 10 06 PM" src="https://user-images.githubusercontent.com/6335974/111110814-709e5280-851a-11eb-8f74-4202921ee7e2.png">

**Comment by eliataylor** [comment]
@Branyer , lo aparece que no podemos usar Firebase CDN (<script>) y Module Imports (Import Firebase from ..) juntos. Yo preferiría usar el CDN, pero de las dependencias de FireCMS, no se si tenemos la opcion?

**Comment by Branyer** [comment]
tambien estuve viendo este problema, la cosa es que fireCMS requiere que firebase este importado en su scope, quizas una opción podria ser, en un archivo inicializar firebase con la configuracion y en ese archivo exportarlo a todo lugar de la app que lo necesite. que piensas? no estoy seguro de si el CDN podria funcionar.

**Comment by eliataylor** [comment]
Si esta posible a crear una piel de FIreCMS, debemos cambiar el todo a `Import`. (Uno motivo, es me gustaria usar los [collections](https://github.com/eliataylor/clock-agendas/tree/master/src/views/firebaseCMS/collections), campos, y Validators de FireCMS dentro nuestros formularios, como #9 .

Si no, depronto debemos se mudar FireCMS por un otro repositorio.

**Comment by Branyer** [comment]
sí, creo que podria ser una buena alternativa el mudar FireCMS, si decides hacerlo, porfa me confirmas y me pasas el nuevo repo para comenzar con esa tarea.

**Comment by eliataylor** [comment]
Ok @Branyer, gracias. Podemos esperar hasta lanzamos el siteo.
