### ISSUE TITLE
Rebuild /about page with DB data

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#24]
Build this page by querying firestore for users with the "boardmember" flag.

https://democraseeclub.web.app/about

**Comment by eliataylor** [comment]
@Branyer  / @Aujemd, estoy llenando Firestore con los datos de Rallies y Resources. Mientras tanto, puedes realizar esta tarea con la intencion de ampliar la conexion con Firestore?

**Comment by Branyer** [comment]
Está bien @eliataylor

**Comment by Branyer** [comment]
Hola @eliataylor, esto está terminado.
