### ISSUE TITLE
Implement FireCMS's `useSideEntityController()`

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#32]
arregla: https://github.com/DemocraseeClub/website/blob/master/src/views/Rallies.js#L35

```
this.props.sideEntityController.open({
            entityId: false,
            collectionPath: "rallies"
        })
        ```

"Start a Rally" deberia abrir el formulario de Rallies si estas autenticado:

![Screen Shot 2021-04-28 at 3 18 17 AM](https://user-images.githubusercontent.com/6335974/116388326-92088480-a7d0-11eb-9cbb-b5eda41e9fa7.png)

**Comment by Branyer** [comment]
Hola Eli, revisando la documentación y los ejemplos de [firecms](https://github.com/Camberi/firecms), encontré que los hooks solo se pueden usar dentro de una [vista adcional](https://github.com/Camberi/firecms/blob/master/example/src/SampleApp/ExampleCMSView.tsx#L15) que se [agrega al Navigation de firecms ](https://github.com/Camberi/firecms/blob/master/example/src/SampleApp/SampleApp.tsx#L133), por eso no se puede usar afuera de ese entorno

**Comment by eliataylor** [comment]
la repuesta de @fgatti675 : https://github.com/Camberi/firecms/issues/72 (dice lo mismo)

**Comment by eliataylor** [comment]
@Branyer , puedes explorar el ejemplo de @fgatti675 aqui:  https://github.com/Camberi/firecms/issues/72#issuecomment-829411425

**Comment by Branyer** [comment]
@eliataylor, ya logre que funcionaran los hooks de fireCMS,  puede verlo en la rama [ testing-fireCMS-hooks](https://github.com/DemocraseeClub/website/tree/testing-fireCMS-hooks)

**Comment by eliataylor** [comment]
@Branyer, me aparece bueno; y suficiente para seguir este manera con los formularios, incluyendo los de autenticación: https://democraseeclub.web.app/login.

Puedes seguir con https://github.com/DemocraseeClub/website/issues/35, y poner el objeto de usuario dentro de Redux para aceso de todos los componentes.
