### ISSUE TITLE
Apply masonry layout to a Card layouts 

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#42]
`/rallies` in particular would look a lot better with a masonry layout.

these tutorials might help:

- https://mdbootstrap.com/docs/react/layout/masonry/
- https://www.npmjs.com/package/react-masonry-css

**Comment by eliataylor** [comment]
(una tarea útil y sencilla... @Branyer / @Aujemd)

**Comment by polinatolkacheva** [comment]
I'm taking this task

**Comment by eliataylor** [comment]
@Aujemd already started and is almost complete with this - https://github.com/DemocraseeClub/website/compare/johan-dev

Johan, por favor, commentas cuando comienzas una tarea :)
