### ISSUE TITLE
Query  & filter Resources

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#44]
query & filter resources en https://democraseeclub.web.app/resources

- on `resouce_type` and maybe `office_hours`

**Comment by eliataylor** [comment]
@Aujemd , puedes comenzar despues que arreglamos los Functions

**Comment by Branyer** [comment]
Eli ya agregue el endpoint de resource_type, ya le comente a Johan

**Comment by Branyer** [comment]
tengo una duda, los endpoints de office_hours, van relacionados a  las propiedades date_end, date_start, o recurring? o todos?

**Comment by Aujemd** [comment]
Ya implementé la query y el filtro

**Comment by eliataylor** [comment]
@Branyer / @Aujemd , 

- A menos que existan necesidades de seguridad, dejamos usar el firebase de web (client side js), ya que usa `web sockets` y ofrece los mismos filtros.

- Escribí un ejemplo en [Resources.js](https://github.com/DemocraseeClub/website/blob/bd71b610a9aad2b670713f5305271f97aa032a7c/src/views/Resources.js#L52) pero, necesito su ayuda con el filtro de `resource_type`.
