### ISSUE TITLE
Fix `Functions` to use Express

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#47]
@Branyer , has probado si necesitamos [rewrites](https://github.com/DemocraseeClub/website/blob/master/firebase.json#L20) en [firebase.json](https://github.com/DemocraseeClub/website/blob/master/firebase.json#L20) cuando estamos usando express por los Functions?

(Cuando yo sube los cambios, se borró `injectMeta` y los otros functions:

![Screen Shot 2021-05-18 at 9 21 20 AM](https://user-images.githubusercontent.com/6335974/118688064-8c440480-b7ba-11eb-96f8-a502e79c2c07.png)

**Comment by Branyer** [comment]
Ok Eli, Ya voy a investigar sobre los rewrites. Lo de que solo aparece app, es porque las functions que he agregado estan dentro de ese app de express, todas estan dentro de app. ya voy a agregar los triggers de createUser, etc. y las functions de envio de emails.
