### ISSUE TITLE
set `created` and `modified` fields on ALL collections as `onPreSave`

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#49]
FireCMS supports a `onPreSave` method on entity definitions. We need something like 

```
officialSchema.onPreSave = ({ values }) => {

  if (!values.created) values.created = new Date().getTime() / 1000;
  values.modified = new Date().getTime() / 1000;

  return values;
};
```

to ensure we can `orderBy(created | modified)`

**Comment by Branyer** [comment]
@eliataylor acabo de subir un commit a mi rama, la idea era plantearte que en lugar de usar FireCMS para modificar los valores de "create" y "modified" se usaran  los triggers de las function de firestore. Lamentablemente firebase no permite escuchar a todos los eventos asi que tendriamos que agregar una function que escuchara las actualizaciones para cada documento. que opinas?

**Comment by eliataylor** [comment]
estaba pensando lo mismo @Branyer. Gracias!

yo copié un ejemplo aquí: https://github.com/DemocraseeClub/website/blob/master/functions/src/index.ts#L212

que piensas? puedes implementarlo?

**Comment by Branyer** [comment]
Si claro @eliataylor ya empiezo con eso, ya ayer lo implemente en  [branyer-dev](https://github.com/DemocraseeClub/website/commit/3a712416e7f6f8cb8736feb01c88a035a6a511a1) para las actualizaciones de usuarios.

**Comment by Branyer** [comment]
Ya esta listo @eliataylor, puedes ver los cambios en la rama [branyer-dev](https://github.com/DemocraseeClub/website/blob/branyer-dev/functions/src/index.ts#L211)

**Comment by eliataylor** [comment]
ahh. entonces, perfecto @Branyer . 

Ha probado que `set` no se crea en un bucle infinito en `onUpdate`?

**Comment by Branyer** [comment]
@eliataylor yeah, valido que no se genere el bucle en esta [linea](https://github.com/DemocraseeClub/website/blob/branyer-dev/functions/src/index.ts#L219), todo funciona bien

**Comment by eliataylor** [comment]
excelente.

merge to master y adelantamos :)

**Comment by eliataylor** [comment]
(una pregunta, tu piensas esta mejor usar `onUpdate` y `onCreate` en lugar de `onWrite` con una condición para `created`?)

**Comment by Branyer** [comment]
a mi me gusta usar mas onUpdate y onCreate, ya que es un poco mas descriptivo y especifico. Pero si quieres se puede implementar el onWrite, al fin y al cabo, los dos llevan al mismo resultado.

**Comment by eliataylor** [comment]
dejalo asi.

podemos cambiarlo si el archivo crezca demasiado.
