### ISSUE TITLE
Import public/json into Firebase DB

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#5]
Currently this page - https://democraseeclub.web.app/rally/hgp/meeting/how-to-get-things-built-day-1 - is driven by this static json public/json/rally/hgp/meeting/how-to-get-things-built-day-1.json structure.

This (or a similar structure) should come from 1 (or more) ajax requests to Firebase API via their javascript client sdk: https://firebase.google.com/docs/reference/js and drive all rallies from this component.

See https://github.com/eliataylor/clock-agendas/blob/master/src/views/RallyHome.js#L34

**Comment by eliataylor** [comment]
@Branyer, de #8, tienes ideas por este (#5)?

(yo tenia un plan como `node tools/prepopulator.js` (https://github.com/eliataylor/clock-agendas/blob/master/tools/prepopulator.js) - pero depronto hay una manera para importer todos Rallies del FireCMS / Cloud Firestore?

**Comment by Branyer** [comment]
Lo que se quiere es crear cada meeting en firebase, y luego en la propiedad **Agenda JSON** de cada meeting, importar los archivos que estan en **_public/json_**?

**Comment by eliataylor** [comment]
Si @Branyer . 

y tendremos que cambiar la estructura  sobre los relaciones a Usarios, y los vocabularios.

**Comment by eliataylor** [comment]
depronto primero debemos hacer una ruta en #19 para ver la estructura de la repuesta de Firebase.

**Comment by eliataylor** [comment]
done manually
