### ISSUE TITLE
Create User Profile

### ISSUE THREAD

**Issue by Aujemd** [DemocraseeClub/website#50]
Create a page base on 
![image](https://user-images.githubusercontent.com/26072442/119868854-9322f380-beed-11eb-90de-f96d3a9e417b.png)

**Comment by eliataylor** [comment]
:thumbsup:

**Comment by Aujemd** [comment]
Ready https://github.com/DemocraseeClub/website/commit/a2c0a65d68eb8fe410fbdaadac09f424ddb38516
