### ISSUE TITLE
User profile (edit)

### ISSUE THREAD

**Issue by Aujemd** [DemocraseeClub/website#51]
Create page based on
![image](https://user-images.githubusercontent.com/26072442/119869129-e2692400-beed-11eb-95d9-50807668944b.png)

**Comment by eliataylor** [comment]
:thumbsup:

**Comment by Aujemd** [comment]
Complete (UI)
https://github.com/DemocraseeClub/website/commit/6e1d53d2a64d2203c236e6435afc73f015a1c00b
