### ISSUE TITLE
Implement FireCMS

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#8]
This looks promising: https://github.com/Camberi/firecms

We're open to other suggestions but the motivation is to offer our internal team some editorial control until we get the full authenticated site and API completed.

The field and entity Schemas are here: 

- Entities: https://docs.google.com/spreadsheets/d/14JqTgNzR63KTKqUZ7dI7JLK0pZVt-3yRxCTIgt3gSBU/edit#gid=806175863
- Taxonomy: https://docs.google.com/spreadsheets/d/1Jte7GraFn1zHfBaa291_d3csNZy9ifFKqZ6H7zzFL4w/edit#gid=421989747

I wrote a script to output all fields to config files here:  https://github.com/eliataylor/clock-agendas/tree/master/src/fields/configs

**Comment by Branyer** [comment]
Hola, tenia unas dudas, como quieres implementar el firebase CMS? solo un componente al que se pueda acceder por una ruta? o una carpeta aparte dentro del proyecto clock-agendas?

**Comment by eliataylor** [comment]
@Branyer , por favor, nos avisas desde tus pruebas.

**Comment by Branyer** [comment]
he creado este proyecto de prueba: https://github.com/Branyer/fireCMS-test, supongo eso es lo que quieres implementar, mi duda es : de que forma se va a acceder a ese dashboard desde la pagina?

**Comment by eliataylor** [comment]
seria mas facil aqui: democraseeclub.web.app/cms  ?

sin embargo, si dos proyectos de Firebase puede compartir uno baso de datos, lo ponga aqui: democraseeclub-cms.web.app

**Comment by eliataylor** [comment]
@Branyer, me entiendes?

**Comment by Branyer** [comment]
Si claro, ya lo estoy empezando a implementar, cree una rama feature/fireCMS, cuando se accede a url/cms se puede ver el dashboard

**Comment by eliataylor** [comment]
perfecto @Branyer, lo aparece que el metodo [buildSchema](https://github.com/eliataylor/clock-agendas/blob/feature/fireCMS/src/views/FirebaseCMS.tsx#L33) puede usar nuestros [archivos de configuracion](https://github.com/eliataylor/clock-agendas/tree/master/src/fields/configs)

**Comment by Branyer** [comment]
Hola Eli, ya he terminado de construir los schemas y lo he conectado con firebase, ya he subido alguna data de prueba, por favor para que lo revises y me digas si está bien.

**Comment by Branyer** [comment]
se accede con la ruta /cms

**Comment by eliataylor** [comment]
lindo. @Branyer 

![Screen Shot 2021-03-08 at 1 54 43 AM](https://user-images.githubusercontent.com/6335974/110305192-5102a980-7fb1-11eb-872f-8ef1a29656d8.png)

todo funciona.

**Comment by eliataylor** [comment]
@Branyer , una cosa:

el campo "Agenda JSON" es para `type="text"` or `json` 

yo veo `mediaType=json" aqui: https://github.com/eliataylor/clock-agendas/blob/2ca0a145316e5488acd52c500e8c8c0688ffdbea/src/views/firebaseCMS/collections/meeting.js#L97

pero en la pagina esta un imagen:

![Screen Shot 2021-03-08 at 2 00 26 AM](https://user-images.githubusercontent.com/6335974/110306244-73e18d80-7fb2-11eb-867b-3193f0b9c861.png)

**Comment by Branyer** [comment]
Yo lo que pensaba era que se tenia que subir un archivo .json, entonces, para los campos JSON se utiliza un input "text"?

**Comment by eliataylor** [comment]
ahhh.  entiendo.

Pienso que deberiamos utilizar "text" porque cuando la pagina solicita `/rally/hgp/meeting/#` la repuesta deberia tener el json alado (no como un enlace)  - eventualmente crearemos la Agenda como campos, pero esa estructura todavía está cambiando demasiado.

**Comment by eliataylor** [comment]
@Branyer , puedes añadir un validator para confirmar el texto de JSON es valido?

como `try { JSON.parse(agenda) } catch(e) {}`

**Comment by Branyer** [comment]
Sí, creo que fireCMS tiene un metodo onPreSave donde puedo validar eso

**Comment by Branyer** [comment]
listo, ya está como texto, y lo valido antes de enviarlo a firebase.

**Comment by eliataylor** [comment]
hecho! 

gracias @Branyer

**Comment by eliataylor** [comment]
@Branyer , una pregunta:

porque la ruta es `/c/:entity` en lugar de `/cms/:entity` ?

**Comment by Branyer** [comment]
Eso es debido a la libreria https://github.com/Camberi/firecms, por defecto cambia a esa ruta **/c/:entity**

**Comment by eliataylor** [comment]
raro
