### ISSUE TITLE
Implement Create Rally multi-page form (custom)

### ISSUE THREAD

**Issue by eliataylor** [DemocraseeClub/website#9]
https://xd.adobe.com/view/0abb01ec-1d5a-497e-881c-bf7a9ceb064c-5fe8/screen/fa714067-6a33-487b-989c-3ff858ece6d0

<img width="522" alt="Screen Shot 2021-02-28 at 7 10 01 PM" src="https://user-images.githubusercontent.com/6335974/109447474-998df600-79f8-11eb-9d40-98b37d3ed660.png">

**Comment by Aujemd** [comment]
Hola Eli, tengo una pregunta, este issue aún esta por hacer ? si es así para yo comenzarlo

**Comment by eliataylor** [comment]
@Aujemd, aunque estes diseños van a cambiar un poquito, si puedes conectar este formulario con Firebase, por favor comience

**Comment by eliataylor** [comment]
closing this for now
